### ISSUE TITLE
REST version not supported? FORBIDDEN_REST_VERSION

### ISSUE THREAD

**Issue by sleewok** [hyperwallet/php-sdk#102]
I'm trying to get v4 SDK to work with Laravel 8. However, anytime I try to do an API call I am getting an exception "FORBIDDEN_REST_VERSION". I've tried calling listUsers and getProgram. Both give me the same exception.

I'm using the branch that adds support for guzzle 7.

Any help would be greatly appreciated.

**Comment by sleewok** [comment]
This issue is specifically happening on V4. I implemented V3 and it works fine. Do I have to contact hyperwallet to get V4 enabled with the sandbox? 

Is V3 or V4 the recommended API to develop with?

**Comment by grmeyer-hw-dev** [comment]
HI @sleewok 

Are you still facing issue with the PHP SDK ? 

The [Php V4 SDK v2.2.3](https://github.com/hyperwallet/php-sdk/releases/tag/2.2.3) and   [Php V3 SDK v1.7.3](https://github.com/hyperwallet/php-sdk/releases/tag/1.7.3) was released to address PHP-8 support.

Let us know if you face any issue or have some suggestion to improve the SDK.

**Comment by usman149** [comment]
Hi, I'm facing "FORBIDDEN_REST_VERSION" in nodejs while creating users. 
I'm using hyperwallet-sdk.

**Comment by grmeyer-hw-dev** [comment]
> Hi, I'm facing "FORBIDDEN_REST_VERSION" in nodejs while creating users.
> I'm using hyperwallet-sdk.

Hi @usman149, 
I believe that can happen if the company program is configured to use Rest V3 and you are using SDK to connect on V4 or vice-verse.

In case you desire to migrate to use Rest V4, you can contact your account manager or the Hyperwallet Production Support team to use API v4.
For more information about API v4
https://docs.hyperwallet.com/content/api/v4/overview/updates.
