### ISSUE TITLE
Fix your docs links

### ISSUE THREAD

**Issue by kirilkirkov** [hyperwallet/php-sdk#107]
https://packagist.org/packages/hyperwallet/sdk

Documentation is available at http://hyperwallet.github.io/php-sdk - this link dont works!

**Comment by asdfklgash** [comment]
https://docs.hyperwallet.com/content/api/v3/overview/sdk#php + https://docs.hyperwallet.com/content/api/v4/overview/sdk#php

**Comment by grmeyer-hw-dev** [comment]
Hi @kirilkirkov,

Thanks for opening this issue. 

The code [documentation  link](https://hyperwallet.github.io/php-sdk) is fixed . and as @asdfklgash mentioned the Hyperwallet Doc portal will explain how to setup and provide overall samples to use the SDK code.
