### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by specialtactics** [hyperwallet/php-sdk#115]
Hello

PHP 7.x is no longer supported, we really need to move to PHP 8, and this SDK is blocking us

**Comment by grmeyer-hw-dev** [comment]
Hi @specialtactics,

Could you share error you are facing with PHP-8? 

I'm getting requirements to plan this change.

**Comment by grmeyer-hw-dev** [comment]
Hi @specialtactics 

The [Php V4 SDK v2.2.3](https://github.com/hyperwallet/php-sdk/releases/tag/2.2.3) and   [Php V3 SDK v1.7.3](https://github.com/hyperwallet/php-sdk/releases/tag/1.7.3) was released to address PHP-8 support.

Let us know if you face any issue or have some suggestion to improve the SDK.
