### ISSUE TITLE
PHP 8 + v2.2.2 - Error: The information entered does not match our records. Please try again.

### ISSUE THREAD

**Issue by bnski** [hyperwallet/php-sdk#116]
Running the same code under the following package combination works without error or issue on PHP 8.1.

```
"php": "^8.0",
"guzzlehttp/guzzle": "^6.0",
"hyperwallet/sdk": "^1.3",
"laravel/framework": "^8.0"
```

However, the following package combination produces an almost instant error response of `Error: The information entered does not match our records. Please try again.`

```
"php": "^8.1",
"guzzlehttp/guzzle": "7.4.5",
"hyperwallet/sdk": "^2.2.2",
"laravel/framework": "^8.0"
```

The stack trace points to `at vendor/hyperwallet/sdk/src/Hyperwallet/Util/ApiClient.php:198`

I've tried different combinations of Guzzle, PHP, and the HyperWallet SDK without any luck.

Any ideas?

**Comment by grmeyer-hw-dev** [comment]
Hi @bnski 

Could you try `2.2.3` release? 
Our team addressed few issues.

**Comment by grmeyer-hw-dev** [comment]
Hi @bnski,

The `Error: The information entered does not match our records. Please try again.` is because the credential you are providing mind be wrong.

I'd encourage you to contact the Hyperwallet Product Support they can help you.

**Comment by bnski** [comment]
So to confirm, the exact same credentials inserted on the exact same line of code, that work on `"hyperwallet/sdk": "^1.3"` may not work on `"hyperwallet/sdk": "^2.2.2"`?

**Comment by grmeyer-hw-dev** [comment]
@bnski

**Comment by grmeyer-hw-dev** [comment]
@bnski 

Could you give a try with `1.73` that's latest V3 release?

The diff between `1.3` and `2.2.2` is the Rest version, this mind required some configuration on this program but the Hyperwallet Product Support is right to channel contact.

**Comment by bnski** [comment]
I did more testing in my local environment and was able to get some test scripts in prod.  


```
   Hyperwallet\Exception\HyperwalletApiException 

  This REST version is not supported for this program

  at vendor/hyperwallet/sdk/src/Hyperwallet/Util/ApiClient.php:194
    190▕                     )
    191▕                 ));
    192▕             }
    193▕             $errorResponse = new ErrorResponse($e->getResponse()->getStatusCode(), $body);
  ➜ 194▕             throw new HyperwalletApiException($errorResponse, $e);
    195▕         }
    196▕     }
    197▕ 
    198▕     /**

      +14 vendor frames 
  15  routes/console.php:27
      Hyperwallet\Hyperwallet::listUsers()

```

For the same 'build', locally I get the `The information entered does not match our records. Please try again.`, however, in production, I receive `This REST version is not supported for this program` - is this product support?

**Comment by grmeyer-hw-dev** [comment]
That's right @bnski,  you can contact your account manager or the Hyperwallet Production Support team to use API v4.

I'll close this issue, but let us know if you face an issue or need some help with SDK. 

For more information about API v4
https://docs.hyperwallet.com/content/api/v4/overview/updates.
