### ISSUE TITLE
User/ bank account removal.

### ISSUE THREAD

**Issue by sanjotboyal** [hyperwallet/php-sdk#24]
Method for deleting a registered user and/or their existing bank accounts?

**Comment by wmews-hw** [comment]
Hi @sanjotboyal 

Regarding deleting a user it is not supported through rest, but we can close wallets for you when this is required. Our Production Support team will be able to assist

Now for transfer methods like a bank account (as you said), you can use our status transition endpoint to DE_ACTIVATED it.
Please refer to https://portal.hyperwallet.com/docs/api/v3/resources/status-transitions/bank-accounts-create

Let us know if you have any further question.
