### ISSUE TITLE
Add businessOperatingName to user model

### ISSUE THREAD

**Issue by ChristianFranke** [hyperwallet/php-sdk#26]
According to the documentation https://portal.hyperwallet.com/docs/api/v3/resources/users/create the entity `user` should have a parameter named `businessOperatingName`, which is actually missing (https://hyperwallet.github.io/php-sdk/master/Hyperwallet/Model/User.html). Could you please add it to your sdk?

Thank you!

**Comment by grmeyer-hw-dev** [comment]
Hi @ChristianFranke 

Thanks for opening this issue. I'm assuming this is old issue and the field is available into the latest version of the SDK.
