### ISSUE TITLE
Cannot install on Laravel 8

### ISSUE THREAD

**Issue by dungnh** [hyperwallet/php-sdk#73]
I got an issue when tried to install with Laravel 8.

`- Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - hyperwallet/sdk 2.1.0 requires guzzlehttp/guzzle ^6.2.1 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for hyperwallet/sdk ^2.1 -> satisfiable by hyperwallet/sdk[2.1.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].`

Please help to check and upgrade the guzzlehttp/guzzle to version 7.x

**Comment by specialtactics** [comment]
when you do composer update, include the guzzle package. Laravel 8 still supports guzzle 6.

That being said, yeh SDK should be updated to support either.

**Comment by Kladislav** [comment]
i have problem with that, cause i have another package that requires guzzle ^7.1

**Comment by specialtactics** [comment]
Opened PRs for both v3 and v4, the next problem is HW is running tests for very old versions of php...

**Comment by specialtactics** [comment]
If you guys haven't already resolved it yourselves, you can use our fork until this is merged into this repo.

v3 api
https://github.com/CoverGenius/php-sdk/tree/feature/support-guzzle-7
v4 api
https://github.com/CoverGenius/php-sdk/tree/feature/support-guzzle-7-master

**Comment by asdfklgash** [comment]
Is there any news on that topic?
We're running on Laravel 8 and need to use Guzzle 7 for some other internal topics.

**Comment by Ludovic36** [comment]
Any news about the merge? To get guzzle 7 compatibility or should i have to use an other compatible sdk as mentioned? Thanks.
