### ISSUE TITLE
Remove unsupported versions of PHP from unit tests, move towards PHP 8

### ISSUE THREAD

**Issue by specialtactics** [hyperwallet/php-sdk#89]
PHP versions 5.6 and 7.0 haven't had security support - let alone feature support for many years, and contain serious security vulnerabilities. HHVM is not an official build of php, and the entire php ecosystem moved on from it a decade ago.

I propose these versions of PHP be removed from the unit testing, and meanwhile newer versions which are supported added. Furthermore, you should begin on working on PHP 8 support. These items are extremely necessary for us at Cover Genius.

If some clients wish to use those PHP versions they would still be able to do so using current tags, so there should be zero issues with that for legacy installations.

However as the PHP ecosystem has long moved forward, you need to be moving with it, otherwise you are creating a blocker for other clients like us, who are unable to use your SDK with an up to date stack.

This is currently a blocker for https://github.com/hyperwallet/php-sdk/issues/73

**Comment by specialtactics** [comment]
I've included these changes in my PRs here which are to update to allow for guzzle 7, which is also a necessary step on modernising the dependencies.

https://github.com/hyperwallet/php-sdk/pull/87
https://github.com/hyperwallet/php-sdk/pull/88

**Comment by grmeyer-hw-dev** [comment]
Hi @specialtactics 

The [Php V4 SDK v2.2.3](https://github.com/hyperwallet/php-sdk/releases/tag/2.2.3) and   [Php V3 SDK v1.7.3](https://github.com/hyperwallet/php-sdk/releases/tag/1.7.3) was released to address PHP-8 support.

Let us know if you face any issue or have some suggestion to improve the SDK.
